sudo: required
services:
  - docker

before_install:
  - docker build -t ankurkumargautam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ankurkumargautam/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-AG"
  env: "DockerReactAg-env"
  bucket_name: "elasticbeanstalk-us-east-1-152001540459"
  bucket_path: "docker-react-AG"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"