sudo: required
services:
  - docker

before_install:
  - docker build -t ankurkumargautam/docker-react -f Dockerfile.dev .

script:
  - docker run ankurkumargautam/docker-react npm run test -- --coverage